const CHECK_AUTH = "CHECK_AUTH"
const CHECK_AUTH_SUCCESS = "CHECK_AUTH_SUCCESS"
const CHECK_AUTH_FAIL = "CHECK_AUTH_FAIL"
const CHECK_AUTH_GG_SUCCESS = "CHECK_AUTH_GG_SUCCESS"
const CHECK_AUTH_GG_FAIL = "CHECK_AUTH_GG_FAIL"
const SIGN_OUT = "SIGN_OUT"
const FETCH_TOKEN = "FETCH_TOKEN"
const FETCH_TOKEN_SUCCESS = "FETCH_TOKEN_SUCCESS"
const FETCH_TOKEN_FAIL = "FETCH_TOKEN_FAIL"

const AUTH_TYPES = {
    CHECK_AUTH,
    CHECK_AUTH_SUCCESS,
    CHECK_AUTH_FAIL,
    CHECK_AUTH_GG_SUCCESS,
    CHECK_AUTH_GG_FAIL,
    SIGN_OUT,
    FETCH_TOKEN,
    FETCH_TOKEN_SUCCESS,
    FETCH_TOKEN_FAIL
}

export default AUTH_TYPES