const CHECK_AUTH = "CHECK_AUTH"
const CHECK_AUTH_SUCCESS = "CHECK_AUTH_SUCCESS"
const CHECK_AUTH_FAIL = "CHECK_AUTH_FAIL"

const AUTH_TYPES = {
    CHECK_AUTH,
    CHECK_AUTH_SUCCESS,
    CHECK_AUTH_FAIL
}

export default AUTH_TYPES