const CHECK_AUTH = "CHECK_AUTH"
const CHECK_AUTH_SUCCESS = "CHECK_AUTH_SUCCESS"
const CHECK_AUTH_FAIL = "CHECK_AUTH_FAIL"
const CHECK_AUTH_GG_SUCCESS = "CHECK_AUTH_GG_SUCCESS"
const CHECK_AUTH_GG_FAIL = "CHECK_AUTH_GG_FAIL"
const SIGN_OUT = "SIGN_OUT"

const AUTH_TYPES = {
    CHECK_AUTH,
    CHECK_AUTH_SUCCESS,
    CHECK_AUTH_FAIL,
    CHECK_AUTH_GG_SUCCESS,
    CHECK_AUTH_GG_FAIL,
    SIGN_OUT
}

export default AUTH_TYPES