const FETCH_CAMPAIGN = "FETCH_CAMPAIGN"
const FETCH_CAMPAIGN_SUCCESS = "FETCH_CAMPAIGN_SUCCESS"
const FETCH_CAMPAIGN_FAIL = "FETCH_CAMPAIGN_FAIL"

const C_CAMPAIGN = "C_CAMPAIGN"
const C_CAMPAIGN_SUCCESS = "C_CAMPAIGN_SUCCESS"
const C_CAMPAIGN_FAIL = "C_CAMPAIGN_FAIL"

const U_CAMPAIGN = "U_CAMPAIGN"
const U_CAMPAIGN_SUCCESS = "U_CAMPAIGN_SUCCESS"
const U_CAMPAIGN_FAIL = "U_CAMPAIGN_FAIL"

const D_CAMPAIGN = "D_CAMPAIGN"
const D_CAMPAIGN_SUCCESS = "D_CAMPAIGN_SUCCESS"
const D_CAMPAIGN_FAIL = "D_CAMPAIGN_FAIL"



const CAMPAIGN_TYPES = {
    FETCH_CAMPAIGN,
    FETCH_CAMPAIGN_SUCCESS,
    FETCH_CAMPAIGN_FAIL,
    C_CAMPAIGN,
    C_CAMPAIGN_SUCCESS,
    C_CAMPAIGN_FAIL,
    U_CAMPAIGN,
    U_CAMPAIGN_SUCCESS,
    U_CAMPAIGN_FAIL,
    D_CAMPAIGN,
    D_CAMPAIGN_SUCCESS,
    D_CAMPAIGN_FAIL
}

export default CAMPAIGN_TYPES