const FETCH_CONTACT_GROUP = "FETCH_CONTACT_GROUP"
const FETCH_CONTACT_GROUP_SUCCESS = "FETCH_CONTACT_GROUP_SUCCESS"
const FETCH_CONTACT_GROUP_FAIL = "FETCH_CONTACT_GROUP_FAIL"

const C_CONTACT_GROUP = "C_CONTACT_GROUP"
const C_CONTACT_GROUP_SUCCESS = "C_CONTACT_GROUP_SUCCESS"
const C_CONTACT_GROUP_FAIL = "C_CONTACT_GROUP_FAIL"

const U_CONTACT_GROUP = "U_CONTACT_GROUP"
const U_CONTACT_GROUP_SUCCESS = "U_CONTACT_GROUP_SUCCESS"
const U_CONTACT_GROUP_FAIL = "U_CONTACT_GROUP_FAIL"

const D_CONTACT_GROUP = "D_CONTACT_GROUP"
const D_CONTACT_GROUP_SUCCESS = "D_CONTACT_GROUP_SUCCESS"
const D_CONTACT_GROUP_FAIL = "D_CONTACT_GROUP_FAIL"



const CONTACT_GROUP_TYPES = {
    FETCH_CONTACT_GROUP,
    FETCH_CONTACT_GROUP_SUCCESS,
    FETCH_CONTACT_GROUP_FAIL,
    C_CONTACT_GROUP,
    C_CONTACT_GROUP_SUCCESS,
    C_CONTACT_GROUP_FAIL,
    U_CONTACT_GROUP,
    U_CONTACT_GROUP_SUCCESS,
    U_CONTACT_GROUP_FAIL,
    D_CONTACT_GROUP,
    D_CONTACT_GROUP_SUCCESS,
    D_CONTACT_GROUP_FAIL
}

export default CONTACT_GROUP_TYPES