const FETCH_CONTACT = "FETCH_CONTACT"
const FETCH_CONTACT_SUCCESS = "FETCH_CONTACT_SUCCESS"
const FETCH_CONTACT_FAIL = "FETCH_CONTACT_FAIL"

const C_CONTACT = "C_CONTACT"
const C_CONTACT_SUCCESS = "C_CONTACT_SUCCESS"
const C_CONTACT_FAIL = "C_CONTACT_FAIL"

const U_CONTACT = "U_CONTACT"
const U_CONTACT_SUCCESS = "U_CONTACT_SUCCESS"
const U_CONTACT_FAIL = "U_CONTACT_FAIL"

const D_CONTACT = "D_CONTACT"
const D_CONTACT_SUCCESS = "D_CONTACT_SUCCESS"
const D_CONTACT_FAIL = "D_CONTACT_FAIL"



const CONTACT_TYPES = {
    FETCH_CONTACT,
    FETCH_CONTACT_SUCCESS,
    FETCH_CONTACT_FAIL,
    C_CONTACT,
    C_CONTACT_SUCCESS,
    C_CONTACT_FAIL,
    U_CONTACT,
    U_CONTACT_SUCCESS,
    U_CONTACT_FAIL,
    D_CONTACT,
    D_CONTACT_SUCCESS,
    D_CONTACT_FAIL
}

export default CONTACT_TYPES