const FETCH_MAIL_TEMPLATE = "FETCH_MAIL_TEMPLATE"
const FETCH_MAIL_TEMPLATE_SUCCESS = "FETCH_MAIL_TEMPLATE_SUCCESS"
const FETCH_MAIL_TEMPLATE_FAIL = "FETCH_MAIL_TEMPLATE_FAIL"

const C_MAIL_TEMPLATE = "C_MAIL_TEMPLATE"
const C_MAIL_TEMPLATE_SUCCESS = "C_MAIL_TEMPLATE_SUCCESS"
const C_MAIL_TEMPLATE_FAIL = "C_MAIL_TEMPLATE_FAIL"

const U_MAIL_TEMPLATE = "U_MAIL_TEMPLATE"
const U_MAIL_TEMPLATE_SUCCESS = "U_MAIL_TEMPLATE_SUCCESS"
const U_MAIL_TEMPLATE_FAIL = "U_MAIL_TEMPLATE_FAIL"

const D_MAIL_TEMPLATE = "D_MAIL_TEMPLATE"
const D_MAIL_TEMPLATE_SUCCESS = "D_MAIL_TEMPLATE_SUCCESS"
const D_MAIL_TEMPLATE_FAIL = "D_MAIL_TEMPLATE_FAIL"



const MAIL_TEMPLATE_TYPES = {
    FETCH_MAIL_TEMPLATE,
    FETCH_MAIL_TEMPLATE_SUCCESS,
    FETCH_MAIL_TEMPLATE_FAIL,
    C_MAIL_TEMPLATE,
    C_MAIL_TEMPLATE_SUCCESS,
    C_MAIL_TEMPLATE_FAIL,
    U_MAIL_TEMPLATE,
    U_MAIL_TEMPLATE_SUCCESS,
    U_MAIL_TEMPLATE_FAIL,
    D_MAIL_TEMPLATE,
    D_MAIL_TEMPLATE_SUCCESS,
    D_MAIL_TEMPLATE_FAIL
}

export default MAIL_TEMPLATE_TYPES