const SEND_MAIL = "SEND_MAIL"
const SEND_MAIL_SUCCESS = "SEND_MAIL_SUCCESS"
const SEND_MAIL_FAIL = "SEND_MAIL_FAIL"

const MAIL_TYPES = {
    SEND_MAIL,
    SEND_MAIL_FAIL,
    SEND_MAIL_SUCCESS,
}

export default MAIL_TYPES